### ISSUE TITLE
access to dev documentation is broken 

### ISSUE THREAD

**Issue by diginet-md** [piwik/developer-documentation#102]
pls. visit
http://developer.piwik.org/api-reference
you will see empty page

**Comment by tsteur** [comment]
Thx a lot! Should were again http://developer.piwik.org/api-reference

**Comment by tsteur** [comment]
I think problem is when switching between branches. In one branch `.gitattributes` is present in other not (eg latest stable). I really tried for long time to fix even this morning and again and don't know how to fix... so workaround for dev docs would be to only generate docs for `master` and not for latest stable anymore (we are not displaying it currently anyway)

**Comment by mattab** [comment]
@diosmosis Thomas also got hit by the gitattributes train. maybe we can figure something out, or remove the file from github if it introduces issues once more in the future
