### ISSUE TITLE
Support switching between Piwik versions

### ISSUE THREAD

**Issue by tsteur** [piwik/developer-documentation#138]
I think it will be good to be able to switch between Piwik versions. At least between Piwik 2 and 3.

For auto generated docs it's actually not too hard I think to generate documentation for different versions as we used to do this already but never exposed it to the UI. There were maybe a view problems though.

We would also need this for the regular guides though. So the task would be to move all docs into a subfolder that contains the Piwik version. Eg `docs/2.0/...` and `docs/3.0/...` ideally it would at some point work for all patch versions and whenever there is a new release we simply older docs unchanged and make changes only on new version. Lots of duplicated content though so we need to make sure maybe to only index the docs for latest version.

As of the UI we will need to add a version selector and likely even have more "speaking" URLs. Ideally it was something like `/3.0/guides/...` where `/guides/...` would point to latest version to keep links active. However, for simplicity, we might instead save the selected Piwik in a cookie instead. Not sure if this is good or bad for SEO, maybe rather bad as it might not index correct version or something? I think as long as we serve the latest version by default it might be ok. For now I'll add a version selector next to "Search"

**Comment by tsteur** [comment]
Any feedback on how we should handle the changelog? 

Meaning different changelog for each version eg for 2.X a separated changelog and a different one for 3.X or a combined one?

I'll go for a combined one for now. We don't expect many 2.X releases anymore anyway and this way a user can see everything in one page

**Comment by tsteur** [comment]
Actually, I think we kind of need to have the Piwik version in the URL re SEO and not saved in a cookie as the same resource would serve different content depending on the cookie and this might not good for SEO.

We could have `/latest/...` to fetch always docs for the latest version. Then we also have `/3x/...` and `/2x/` in the URL or something similar. Eg `developer.piwik.org/latest/guides/myguide`

**Comment by tsteur** [comment]
@mattab as some URLs will serve same content under different URLs should we set for these pages a rel= canonical or a noindex ?  https://moz.com/learn/seo/duplicate-content

**Comment by mattab** [comment]
by adding support for different Piwik versions in the Developer docs, we really help our users be successful with Piwik whether they use LTS or the latest major version. :+1: 


Feedback
* unified changelog: :+1:  
* URLs: +1 to use the current URLs to show the "latest" piwik version. (good to have short default urls)
* Duplicate content: I think it makes sense to use "<link rel="canonical" href="` and link to our short URLs without version number, if the page still exists. If the "old page" does not exist anymore in latest Piwik docs, then we wouldn't show the canonical meta tag.

> When there is a new Piwik version we will pretty much only need to increase an integer.

great! added this as step in our beta1 checklist, which we can reuse later when releasing Piwik 4 etc. https://github.com/piwik/piwik/issues/8836 

> If someone is viewing a guide or a reference I am now also showing a link at the top that lets someone directly read the article for the latest Piwik version

:+1:
