### ISSUE TITLE
Make distributing-your-plugin guide "global"

### ISSUE THREAD

**Issue by tsteur** [piwik/developer-documentation#144]
This guide should not be version specific as it is pretty much the same for all Piwik versions. At least for now. Otherwise, when we make changes on the Marketplace, we need to update them everywhere. There might be some things versions specific like < 2.16.3 will not be able to handle all kind of composer version definitions (https://getcomposer.org/doc/articles/versions.md) but it there shouldn't be much of a difference otherwise

**Comment by mattab** [comment]
Sounds good! Is it as simple as moving the guides up one level and deleting the copies?

**Comment by tsteur** [comment]
Yep. We need to delete the guide under docs/2.X and move the guide from docs/3.x to /docs.

I think the only think we'd need to change is to mention "For more information read the Composer Versions documentation." works currently only from Piwik 3.0
