### ISSUE TITLE
Getting Started Part III not linked to

### ISSUE THREAD

**Issue by Findus23** [piwik/developer-documentation#199]
I just noticed that there is a guide that isn't linked from anywhere:
https://developer.piwik.org/guides/getting-started-part-3

In addition the second part is a redirect to the non-existent page:
https://developer.piwik.org/guides/report

**Comment by tsteur** [comment]
If I remember correctly the guides were too complicated and we took them down. I think parts of it are now here: https://developer.piwik.org/guides/custom-reports and here: https://developer.piwik.org/guides/custom-reports-extended

**Comment by tsteur** [comment]
Also I think we basically only wanted in the end a setting up guide and then let users go towards the other guides depending on what they want to do. We used to show this custom report guide, but not all users actually want to create such a report but instead maybe hook to some events and alter the output etc.

**Comment by Findus23** [comment]
In that case it may be helpful to remove the third part and rename the first one, so users aren't looking for other parts.

**Comment by tsteur** [comment]
Definitely 👍

**Comment by Findus23** [comment]
While adding the search I noticed that https://developer.piwik.org/guides/piwik-configuration is also linked from nowhere.
I also saw that some guides are broken. It seems like they are missing a category: `No category defined for guide marketplace`
- https://developer.piwik.org/guides/marketplace
- https://developer.piwik.org/guides/plugins
- https://developer.piwik.org/guides/angularjs-getting-started
- https://developer.piwik.org/guides/introduction

**Comment by tsteur** [comment]
Not sure what to do aobut the piwik-configuration guide, it doesn't really explain much there and the https://developer.piwik.org/guides/piwiks-ini-configuration is linked in the "Piwik In Depth" menu. We could link the config guide though under "Develop => Utils"? No big thoughts on this.

By the looks marketplace guide got replaced by https://developer.piwik.org/guides/distributing-your-plugin

"introduction.md" and "plugins.md" look like old guides from a first draft or so and can be deleted I'd say.

I reckon https://github.com/piwik/developer-documentation/blob/master/docs/3.x/angularjs-getting-started.md could be linked somewhere under "Piwik in depth"?

Yes https://raw.githubusercontent.com/piwik/developer-documentation/master/docs/3.x/develop-utils.md is needed for the menu structure maybe

**Comment by Findus23** [comment]
To be honest I still haven't fully understood how the site structure is generated, so I'd be glad if you could make the changes if you have some time left.

**Comment by tsteur** [comment]
This took me a while to understand as well. I will have a look when I find some time.

**Comment by tsteur** [comment]
@Findus23 issued https://github.com/piwik/developer-documentation/pull/204

**Comment by Findus23** [comment]
This got solved in #204
