### ISSUE TITLE
Update recommended coding standards on the "Contributing to Mamoto Core" page

### ISSUE THREAD

**Issue by nina-py** [piwik/developer-documentation#370]
This page: https://developer.matomo.org/guides/contributing-to-piwik-core has the following lines:

> Make sure your code follows the PSR 1, PSR 2 and PSR-4 coding standards.

On following the link to the PSR 2 standard, I see that it's been deprecated for just over a year:

> Deprecated - As of 2019-08-10 PSR-2 has been marked as deprecated. PSR-12 is now recommended as an alternative.

Solution: link to the PSR-12 standard instead?

**Comment by tsteur** [comment]
Sounds good @nina-py  👍  do you mind creating a PR?

**Comment by nina-py** [comment]
> Sounds good @nina-py +1 do you mind creating a PR?

Not at all, will do asap.

**Comment by nina-py** [comment]
Thanks Thomas for merging the pull request!
