### ISSUE TITLE
Contradictory plugin migration guide from Matomo 3.x to 4.0?

### ISSUE THREAD

**Issue by DevDavido** [piwik/developer-documentation#371]
In the section [Adjust the required Matomo version](https://developer.matomo.org/guides/migrate-matomo-3-to-4#adjust-the-required-matomo-version) it's written:

> We no longer support plugins that support multiple major Matomo versions such as Matomo 3 and Matomo 4: "matomo": ">=3.0.0-b1,<5.0.0-b1". You would in this case receive an error email and the release would not be published.

At the same time, only plugins that span support over multiple major versions get the version selection on their plugin page on matomo.org as shown in the [blog announcement](https://matomo.org/blog/2020/08/matomo4-make-your-plugin-compatible-now/#:~:text=How%20do%20I%20know%20my%20plugin%20changes%20were%20released%20successfully?).

Am I misunderstanding the migration guide?

**Comment by Findus23** [comment]
Hi,

I think the solution lies in the sentence a few paragraphs above: https://github.com/matomo-org/developer-documentation/commit/bef562f63cca7d015ece6f5e0856710ea13e0038

>  We recommend you create a new branch for your plugin that supports Matomo 4. For example `4.x-dev`. This way you will be able to make changes to your plugin for Matomo 3 and Matomo 4 and release independent versions for each of them. You can still publish updates to your plugin that supports Matomo 3 once you have published an update for a version that supports Matomo 4.

So you can support Matomo 3 and 4 at the same time in two separate branches.

**Comment by DevDavido** [comment]
In my case I did that, created another branch [`4.x-dev`](https://github.com/DevDavido/performance-audit-plugin/tree/4.x-dev) but no version selection on the [Matomo plugin page](https://plugins.matomo.org/PerformanceAudit).

**Comment by Findus23** [comment]
Hi,

I have forwarded this to the team and indeed something wasn't working perfectly fine yet. It should show up correctly now.

**Comment by michalkleiner** [comment]
I believe this question has been answered, but please do let us know if you think the documentation should be improved in some way.
