### ISSUE TITLE
"Piwik Git repository" link in tracking-javascript.md is a 404

### ISSUE THREAD

**Issue by slaweet** [piwik/developer-documentation#376]
https://matomo.org/participate/contributing-with-git/ in https://github.com/matomo-org/developer-documentation/blob/live/docs/4.x/tracking-javascript.md#L147
results in
![Screenshot from 2020-08-25 14-18-24](https://user-images.githubusercontent.com/1254342/91173478-31bfc100-e6de-11ea-840c-c804e6129b75.png)

**Comment by tsteur** [comment]
Thanks @slaweet this should be fixed now
