### ISSUE TITLE
Split Javascript Tracking reference into guide + API reference

### ISSUE THREAD

**Issue by mnapoli** [piwik/developer-documentation#42]
Current problems:
- the [Javascript Tracking client](http://developer.piwik.org/api-reference/tracking-javascript) API reference is very long and is a mix of "API reference" and "User guide"
- the "Track your application" section in **Integrate Piwik** doesn't have much content, all the content is in user guides

Solution:

Split the current API reference into:
- a user guide that will be in "Integrate Piwik"
- an API reference that will stay where it is

Given this article is linked to a lot, we need to add a visible link at the beginning of the API reference to make users aware that a detailed user guide exist.

**Comment by mattab** [comment]
Approximately 15 user guides and FAQs pointing to old urls and anchors have been updated
