### ISSUE TITLE
search and piwik-in-depth is broken in 3.x docs 

### ISSUE THREAD

**Issue by Findus23** [piwik/developer-documentation#437]
Both `/3.x/data/documents` and `/3.x/piwik-in-depth` fail with `An exception has been thrown during the rendering of a template ("The requested documentation does not exist: tracking-requests").`

This seems to be because of 
https://github.com/matomo-org/developer-documentation/blob/5528570f52307666889952c36276e0257b1c0176/app/helpers/Content/Category/DevelopInDepthCategory.php#L35
as this guide is not available in 3.x

**Comment by tsteur** [comment]
Thanks for reporting @Findus23 this works now
