### ISSUE TITLE
Developer Document - tracking consent

### ISSUE THREAD

**Issue by Birkaransingh94** [piwik/developer-documentation#539]
I was reading through <https://developer.matomo.org/guides/tracking-consent>; to implement cookie consent for visitors. I will allow my users to opt out of cookies using _paq.push(['forgetCookieConsentGiven']) and to opt out of tracking altogether with _paq.push(['optUserOut']);.

I am using checkboxes. I populate the tracking opt-out checkbox using this.isUserOptedOut();. 

**Is there a similar function to check if a user has consented to cookies?**

**Comment by Findus23** [comment]
I think `this.areCookiesEnabled()` is what you are looking for:
https://github.com/matomo-org/matomo/blob/5d4925d6cde7a71ebeafeddf47357f9455dc9647/js/piwik.js#L5891-L5897

**Comment by tsteur** [comment]
additionally to `areCookiesEnabled` there is also `getRememberedCookieConsent()` method which returns a timestamp of when cookie consent was given.
