### ISSUE TITLE
Markdown character … does not render

### ISSUE THREAD

**Issue by mattab** [piwik/developer-documentation#55]
In the page: docs/piwik-on-the-command-line.md and other pages of the site we use the character `…` but it is not rendered correctly eg. `to ease developmentâ€¦` in http://developer.piwik.org/guides/piwik-on-the-command-line

Goal is to either fix the bug if possible or change characters to three dots characters as a hack.

**Comment by rutsky** [comment]
``…`` is correctly rendered in UTF-8 encoding. You can see it by selecting Unicode encoding in ``View`` -> ``Character Encoding`` Firefox menu.

Proper fix is to specify page character encoding, e.g. by adding

    <meta charset="utf-8">

to https://github.com/piwik/developer-documentation/blob/master/app/templates/base.twig header.

**Comment by mattab** [comment]
Hi @rutsky
thanks much for the tip!! we hope to see more of your comments :-)

**Comment by mnapoli** [comment]
:+1: thanks!

**Comment by rutsky** [comment]
Glad to help :)
