### ISSUE TITLE
 developer-documentation/docs/4.x/database-schema.md : miscounting...

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/developer-documentation#566]
https://github.com/matomo-org/developer-documentation/blob/591885efd8b6e0dcc0f2a9511a33755b23a0b849/docs/4.x/database-schema.md#log-data

> There are **four** types of log data:
> - visits
> - action types
> - plugin specific actions
> - conversions
> - ecommerce items

should be 5 instead of 4... ;-)

I seems also the information in developer-documentation/docs/4.x/log-data.md is not the same

**Comment by justinvelluppillai** [comment]
Thanks @heurteph-ei 👍
