### ISSUE TITLE
how to excute syncronous tracking

### ISSUE THREAD

**Issue by mkassir95** [piwik/developer-documentation#575]
I want to  track an event syncronously , in other ways I want to execute the tracking function and block the rest of the code until the tracking is completed

**Comment by tsteur** [comment]
Hi @mkassir95 

Please ask this question in our forum: https://forum.matomo.org/

Unfortunately, we generally don't answer questions in this issue tracker and only manage bug reports and feature requests. Sorry about the inconvience.
