### ISSUE TITLE
Tacking Device Type through http API

### ISSUE THREAD

**Issue by mkassir95** [piwik/developer-documentation#576]
Which paramter should I pass to the http request in order to track the device type (android , ios ....) ?
I checked that there is a resolution paramter in http API reference but I did not find a paramter for device type

**Comment by tsteur** [comment]
Hi @mkassir95 as far as I know the device type is extracted from the user agent. Meaning you would need to supply the user agent for that device and our [device detector](https://github.com/matomo-org/device-detector/) would need to support it. 

In the future be great to ask such questions in our forum https://forum.matomo.org/ as we usually don't answer questions here as we only manage bugs and enhancements here.
