### ISSUE TITLE
Errors in links of API Reference > Database schema page

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/developer-documentation#593]
## Page / Chapter: https://developer.matomo.org/guides/database-schema#multi-channel-conversion-attribution
The link label is wrong (should not be `Activity Log` but `Multi Channel Conversion Attribution`):
> ### Multi Channel Conversion Attribution
> Learn more about [Activity Log](https://matomo.org/docs/multi-channel-conversion-attribution/).

## Page / Chapter: https://developer.matomo.org/guides/database-schema#activity-log
The link target is dead:
> ### Activity Log
> Learn more about [Activity Log](https://matomo.org/docs/activity-log/).

**Comment by tsteur** [comment]
Thanks for mentioning @heurteph-ei
