### ISSUE TITLE
Missing information on https://matomo.org/docs/embed-matomo-reports/ page

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/developer-documentation#602]
Happy new year, Matomo community!

On Forum ([What are the embedded widget parameters?](https://forum.matomo.org/t/what-are-the-embedded-widget-parameters/29772)), some user complains not having access to all widgets parameters.
He founded `show_footer=0` in order to remove the footer.
Is it possible to update the documentation ([Embedding Matomo Reports in Other Websites or Apps](https://matomo.org/docs/embed-matomo-reports/)) in order to display the whole list of parameters?

**Comment by tsteur** [comment]
Thanks @heurteph-ei . That's done

**Comment by heurteph-ei** [comment]
@tsteur Just to be sure, is there no other parameter?

**Comment by tsteur** [comment]
@heurteph-ei there are but they are not necessarily all "official/supported" and more internal and could change any time. I wouldn't want to document all of them just now as I would make them all an "API" and we'd have to keep supporting them. 

Without testing I would assume that these parameters are likely available: https://github.com/matomo-org/matomo/blob/4.6.2/core/ViewDataTable/Config.php#L106-L134

Different parameters would be supported by different reports.
