### ISSUE TITLE
Start documentation for Matomo 5

### ISSUE THREAD

**Issue by sgiehl** [piwik/developer-documentation#675]
As we have started to develop features, that will be included in Matomo 5 only it would be a good time to start the documentation for Matomo 5.

@tsteur could you maybe added the required steps that needs to be done and maybe assign someone to work on it, so we have a `5.x` option in the documentation and can start adding documentation for it?

**Comment by tsteur** [comment]
We would need to follow these instructions: https://developer.matomo.org/guides/release-management#developermatomoorg

We basically need to follow these steps: https://github.com/matomo-org/developer-documentation/#how-to-add-docs-for-a-new-matomo-version

Then replace all mentions of `4.x-dev` by `5.x-dev` in `docs/*.md` and `docs/5.x-dev/*.md` (for example [this page](https://github.com/matomo-org/developer-documentation/pull/233/files)). The docs in `docs/4.x-dev` should remain unchanged.

@justinvelluppillai which team would work on this? It doesn't require access to any server and it's simply following the instructions and creating a PR.

**Comment by justinvelluppillai** [comment]
@tsteur Websites Team could manage this - ping @lance-matomo

**Comment by lance-matomo** [comment]
Yep, I just added a task in Jira for it.

**Comment by michalkleiner** [comment]
Hi @sgiehl and @lance-matomo, is there anything else that needs to be done here or can we close the issue?

**Comment by sgiehl** [comment]
No. That one seems finished.
