### ISSUE TITLE
Dimensions start at 1

### ISSUE THREAD

**Issue by EPNW-Eric** [piwik/developer-documentation#721]
From my understanding, the first custom dimension is `dimension1` and there is no `dimension0`.
If this is true, shouldn't this
https://github.com/matomo-org/developer-documentation/blob/75999a432b31f0ecf445162fe3d810c2cd651f8c/docs/5.x/tracking-api.md?plain=1#L72
be `dimension[1-999]` instead?

It's not that big of a deal but it took me a while to figure out why my `dimension0` wasn't tracked...

**Comment by sgiehl** [comment]
Hi @EPNW-Eric
You're right. That's actually not fully correct. I'll push a commit to fix this. Thanks
