### ISSUE TITLE
Page Generation Time has been Deprecated

### ISSUE THREAD

**Issue by EPNW-Eric** [piwik/developer-documentation#728]
It seems that the `gt_ms` parameter was deprecated [here](https://github.com/matomo-org/matomo/pull/15736/commits/f5e526334294ff96e539715b061715bc38970ec7) a while ago.

The [Tracking HTTP API documentation](https://developer.matomo.org/api-reference/tracking-api) should reflect that, either with a comment, or by simply removing the parameter (since it's not used anyway?).

**Comment by sgiehl** [comment]
Hi @EPNW-Eric
Thanks for the hint. I'll create a PR to remove that from the documentation for Matomo 5.
