### ISSUE TITLE
A/B testing pins the user to a specific variation

### ISSUE THREAD

**Issue by miiimooo** [piwik/developer-documentation#736]
It took me some time to figure this out but after some testing I realized that once Matomo has selected a variation it will store it in the browser's local storage and re-use that information in subsequent calls.

In other words - unless a user clears their local storage - they will stay in the same variation, no matter how much they refresh the page or clear their browser cache. 

It makes sense for A/B testing and is probably what you would expect but it should be pointed out on the FAQ or somewhere in the relevant documentation 

Q: I always get the same variation?
A: It is stored so that the test can be traced consistently

Or something like that. I think I'm not alone not understanding this see e.g. https://forum.matomo.org/t/matomo-a-b-tests-original-version-is-not-getting-tracked/46536

**Comment by AltamashShaikh** [comment]
@miiimooo We have this [FAQ](https://matomo.org/faq/ab-testing/faq_22509/) and it would be great to use the support email for premium features as this is for issues related to Matomo core.
