### ISSUE TITLE
Browser based searching (Ctl-F) should search the entire Matomo Glossary Page

### ISSUE THREAD

**Issue by atom-box** [piwik/developer-documentation#742]
**Expected:**
Searching glossary.matomo.org (by hitting Ctl-F or similar in a browser) will search all the glossary.

**Actual:**
Hitting Ctl-F only searches the currently selected tab.

**For Example,** 
in this image, (1) will fail because (2) has been selected, even though the sought term is present in (3).
![image](https://github.com/matomo-org/developer-documentation/assets/22874146/e5c2280a-0cd9-43b1-8232-6576af41f9a8)

**Comment by atom-box** [comment]
**Michal commented in Slack:**
We could probably do a JS only search above the tabs that would take you to the first occurrence and highlight the tabs if there were matches in other tabs as well. Or actually remove the tabs and just show the terms with their explanations directly there.

**Comment by atom-box** [comment]
I would claim this is very impactful documentation. As a new user I always felt: 
"Their Glossary is poorly maintained. This is not a serious product. Things are unsearchable and usually missing."
If you think about it, 3 of 4 searches will fail if there are 4 tabs like this and the tabs aren't visible to the browser search.

**Comment by michalkleiner** [comment]
Reopened the core repo issue as that's where the glossary comes from (template and code).
