### ISSUE TITLE
Wrong reference to Region Code at ISO 3166-2 format

### ISSUE THREAD

**Issue by brunocantuaria** [piwik/developer-documentation#752]
Hi everyone,

On Tracking API [reference docs](https://developer.matomo.org/api-reference/tracking-api) it says that if we want to override the value for region/state, we should use the official ISO 3166-2 format. But this is not true.

Here's a [JSON with full ISO 3166-2 ](https://github.com/olahol/iso-3166-2.json/blob/master/iso-3166-2.json
) list of states and here's the [official ISO list](https://www.iso.org/obp/ui/#search) (You need to click on country name to see the regions code) as backproof.

While building an integration I found that any attempt to use the official state code would fail, and turn the region as "Unknown" at Matomo, using the plain name as fallback didn't worked either. The only solution was to replicate the regions code used by GeoIp2 which goes with official code, as [you can see here](https://github.com/matomo-org/matomo-for-wordpress/blob/86f2d679c6d661b8792b24528d5b5976db6794d1/app/plugins/GeoIp2/data/isoRegionNames.php). After following that code structure, Matomo started identifying the regions correctly.

Note that, this list doesn't seems to follow any standard, with regions using 3 characters, mostly using 2 characters and other ones using numeral index.

**Comment by sgiehl** [comment]
Thanks for bringing this up, I'll improve the docs around that.
