### ISSUE TITLE
Update Documentation to Replace "Piwik" with "Matomo"

### ISSUE THREAD

**Issue by dheid** [piwik/developer-documentation#768]
The current developer documentation refers to the software as "Piwik," which has been rebranded as "Matomo." To maintain accuracy and reflect the current state of the product, it is necessary to update all instances of "Piwik" to "Matomo" throughout the documentation.

The name change from "Piwik" to "Matomo" was officially announced long time ago, and it is crucial to align our documentation with the latest branding. Users and developers relying on our documentation should encounter consistent and up-to-date information.

The documentation should consistently refer to the product as "Matomo."

*Additional Context:*

1. The rebranding announcement: https://matomo.org/blog/2018/01/piwik-is-now-matomo/

2. The updated name should be reflected in all code snippets, text, and references within the documentation if it does not break code examples.

**Comment by michalkleiner** [comment]
Hi @dheid, thank you for opening the issue.

We are well aware of the branding change at Matomo and we have already updated the references in the majority of places for Matomo 4 and Matomo 5 documentation. We don't intend to update it for versions 2 and 3 as those are not maintained and somewhat serve as a reflection of the time Matomo used to be named Piwik.

On top of that, some class names, namespaces and code references can't be changed until the code can be changed which may not be possible until the next major version (at this point looking at Matomo 6), so some references, on a case by case basis, need to stay as Piwik.

If you'd like to spend the time and go through the 5.x (primarily) and 4.x (optionally) documentation and highlight places where you think we missed the name change, we would be happy to look at those, of course.
