### ISSUE TITLE
Product view parameters are missing within the HTTP Tracking API documentation

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/developer-documentation#794]
Hi Team,

When debugging the Matomo tracker, we find out that some parameters were missing into: https://developer.matomo.org/api-reference/tracking-api
For example the one about ecommerce product views:
![Screenshot 2024-07-17 at 14 24 46](https://github.com/user-attachments/assets/7eccf87e-6b0c-4fa3-b7ab-3a20b7978e8f)

**Comment by Frankie75321** [comment]
Documentation has been updated. Included four parameters and descriptions for eCommerce Product View Tracking: _pkc, _pkp, _pks, _pkn
