### ISSUE TITLE
Write a guide for tracking single page applications

### ISSUE THREAD

**Issue by tsteur** [piwik/developer-documentation#90]
A user asked for this via the feedback link. I remember we talked about this in the past already but didn't create an issue. We should definitely provide a guide for this.

This will also help us to identify whether there are problems with the current JS tracker when using it in single page applications. I'm sure there are things that can be improved or that are problematic currently.

**Comment by alexandrbig** [comment]
Hello, is there any news regarding this guide?

**Comment by mattab** [comment]
:+1:  this would be extremely valuable, I find more people are asking about this eg. on forums http://forum.piwik.org/t/one-page-website-best-practice/16968

**Comment by shinok01** [comment]
No milestone set for this issue and no one assigned either...would be extremely useful for someone looking to adopt piwiki i guess

**Comment by mattab** [comment]
This was also requested in https://github.com/piwik/piwik/issues/7998#issuecomment-187970497 (now marked as duplicate)

**Comment by BrianPearTree** [comment]
I may have missed the documentation. Why was this closed?

**Comment by TIIUNDER** [comment]
Why is this closed now? The other issue is also closed. Is there any progress in this?

**Comment by TIIUNDER** [comment]
Is there any progress in this?
I found this https://github.com/piwik/developer-documentation/blob/57034f3e2de76d922151ccb24870facfecac2be2/docs/2.x/tracking-javascript-guide.md#track-all-content-impressions-within-a-page

But I'm not sure if this is working.

**Comment by tsteur** [comment]
Where are you after? Or what are you not sure whether it works?

**Comment by TIIUNDER** [comment]
I want to know how to track page changes if the URL was changed by JavaScript (for example hash links or anchor links)

**Comment by tsteur** [comment]
Basically you only need to call `_paq.push(['trackPageView'])` whenever a page changes. Eg if you use angular you can listen to location change success event. You can also update the page title and URL before tracking the pageview like 

```js
_paq.push(['setDocumentTitle', 'eg new page title']);
_paq.push(['setCustomUrl', 'eg new url starting from hash']);
_paq.push(['trackPageView']);
```

**Comment by mattab** [comment]
We've just published the guide, check it out here: [How to track single-page websites and web applications using Piwik Analytics
](https://piwik.org/blog/2017/02/how-to-track-single-page-websites-using-piwik-analytics/)

**Comment by mattab** [comment]
and FAQ: [How do I measure my single-page websites and apps with Piwik?](https://piwik.org/faq/how-to/faq_23636/)

**Comment by wei1215583760** [comment]
I have read the guide:  'How to track single-page websites and web applications using Piwik Analytics'
But i do not know where to place these code

<script type="text/javascript">
var currentUrl = location.href;
window.addEventListener('hashchange', function() {
    _paq.push(['setReferrerUrl', currentUrl]);
     currentUrl = '' + window.location.hash.substr(1);
    _paq.push(['setCustomUrl', currentUrl]);
    _paq.push(['setDocumentTitle', 'My New Title']);

    // remove all previously assigned custom variables, requires Piwik 3.0.2
    _paq.push(['deleteCustomVariables', 'page']); 
    _paq.push(['setGenerationTimeMs', 0]);
    _paq.push(['trackPageView']);
});
</script>

Should i place it at the top or combine with other tracking code together?

**Comment by mattab** [comment]
@wei1215583760 combine with the other tracking code

**Comment by hermann77** [comment]
Here is my simple solution. I could not use 'hashchange' event, because my SPA doesn't use hashes on URLs, so 'hashchange' doesn't fire. Thus use 'click' event:

```
<!-- Matomo -->
  <script type="text/javascript">
    var _paq = window._paq = window._paq || [];
    
    // default tracking (if the page reload completely)
    _paq.push(['trackPageView']);
    _paq.push(['enableLinkTracking']);

    (function() {
      var u="https://MATOMO-INSTANCE-DOMAIN";
      _paq.push(['setTrackerUrl', u+'matomo.php']);
      _paq.push(['setSiteId', '17']);
      var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
      g.type='text/javascript'; g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
    })();

    // ONLY for the SPA because the page doesn't reload on navigation to other pages
    document.body.addEventListener('click', (event) => {
      const clickedUrl = event.originalTarget.href;
      // if a NAVIGATION link (menu item in the SPA) was clicked
      if(clickedUrl) {
        _paq.push(['setCustomUrl', clickedUrl]);
        _paq.push(['trackPageView']);
        _paq.push(['enableLinkTracking']);
      }
    });
  </script>
  <noscript><p><img src="https://MATOMO-INSTANCE-DOMAIN/matomo.php?idsite=17&amp;rec=1" style="border:0;" alt="" /></p></noscript>
  <!-- End Matomo Code -->
```
