### ISSUE TITLE
Add a selection to see docs for Piwik 3.0.0

### ISSUE THREAD

**Issue by tsteur** [piwik/developer-documentation#98]
We will change many API's for Piwik 3.0.0 and it would be nice to be able to select between the versions "Latest 2.X" and "Latest 3.0". At least till 3.0.0 is released but it might be even useful afterwards. 

Without having the possibility to see the docs for 3.0.0 developers won't be able to migrate their plugin to 3.0.0 upfront.

The automated docs are already automatically created for master and the latest stable see https://github.com/piwik/developer-documentation/tree/master/docs/generated but there's no selection for it. Ideally we would also show the related guides when selecting "2.x" so we could maybe at some point just copy everything in docs into a "2.X" folder and leave them there until maybe 6 months after the 3.0 release.

**Comment by mattab** [comment]
Duplicates https://github.com/piwik/developer-documentation/issues/138
